require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GroceryListItemsController, :type => :controller do
  before do
    @request.env["devise.mapping"] = Devise.mappings[:user]
    @user = create(:user, :confirmed)
    @grocery_list = create(:grocery_list, user: @user)
    sign_in @user
  end
  
  # This should return the minimal set of attributes required to create a valid
  # GroceryListItem. As you add validations to GroceryListItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'Apples', grocery_list_id: @grocery_list.id }
  }

  let(:invalid_attributes) {
    { name: '', grocery_list_id: @grocery_list.id }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GroceryListItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all grocery_list_items as @grocery_list_items" do
      grocery_list_item = GroceryListItem.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:grocery_list_items)).to eq([grocery_list_item])
    end
  end

  describe "GET show" do
    it "assigns the requested grocery_list_item as @grocery_list_item" do
      grocery_list_item = GroceryListItem.create! valid_attributes
      get :show, {:id => grocery_list_item.to_param}, valid_session
      expect(assigns(:grocery_list_item)).to eq(grocery_list_item)
    end
  end

  describe "GET new" do
    it "assigns a new grocery_list_item as @grocery_list_item" do
      get :new, {}, valid_session
      expect(assigns(:grocery_list_item)).to be_a_new(GroceryListItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested grocery_list_item as @grocery_list_item" do
      grocery_list_item = GroceryListItem.create! valid_attributes
      get :edit, {:id => grocery_list_item.to_param}, valid_session
      expect(assigns(:grocery_list_item)).to eq(grocery_list_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GroceryListItem" do
        expect {
          post :create, {:grocery_list_item => valid_attributes}, valid_session
        }.to change(GroceryListItem, :count).by(1)
      end

      it "assigns a newly created grocery_list_item as @grocery_list_item" do
        post :create, {:grocery_list_item => valid_attributes}, valid_session
        expect(assigns(:grocery_list_item)).to be_a(GroceryListItem)
        expect(assigns(:grocery_list_item)).to be_persisted
      end

      it "redirects to the created grocery_list_item" do
        post :create, {:grocery_list_item => valid_attributes}, valid_session
        expect(response).to redirect_to(GroceryListItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grocery_list_item as @grocery_list_item" do
        post :create, {:grocery_list_item => invalid_attributes}, valid_session
        expect(assigns(:grocery_list_item)).to be_a_new(GroceryListItem)
      end

      it "re-renders the 'new' template" do
        post :create, {:grocery_list_item => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        { name: 'Updated', grocery_list_id: @grocery_list.id }
      }

      it "updates the requested grocery_list_item" do
        grocery_list_item = GroceryListItem.create! valid_attributes
        put :update, {:id => grocery_list_item.to_param, :grocery_list_item => new_attributes}, valid_session
        grocery_list_item.reload
        expect(grocery_list_item.name).to eq 'Updated'
      end

      it "assigns the requested grocery_list_item as @grocery_list_item" do
        grocery_list_item = GroceryListItem.create! valid_attributes
        put :update, {:id => grocery_list_item.to_param, :grocery_list_item => valid_attributes}, valid_session
        expect(assigns(:grocery_list_item)).to eq(grocery_list_item)
      end

      it "redirects to the grocery_list_item" do
        grocery_list_item = GroceryListItem.create! valid_attributes
        put :update, {:id => grocery_list_item.to_param, :grocery_list_item => valid_attributes}, valid_session
        expect(response).to redirect_to(grocery_list_item)
      end
    end

    describe "with invalid params" do
      it "assigns the grocery_list_item as @grocery_list_item" do
        grocery_list_item = GroceryListItem.create! valid_attributes
        put :update, {:id => grocery_list_item.to_param, :grocery_list_item => invalid_attributes}, valid_session
        expect(assigns(:grocery_list_item)).to eq(grocery_list_item)
      end

      it "re-renders the 'edit' template" do
        grocery_list_item = GroceryListItem.create! valid_attributes
        put :update, {:id => grocery_list_item.to_param, :grocery_list_item => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grocery_list_item" do
      grocery_list_item = GroceryListItem.create! valid_attributes
      expect {
        delete :destroy, {:id => grocery_list_item.to_param}, valid_session
      }.to change(GroceryListItem, :count).by(-1)
    end

    it "redirects to the grocery_list_items list" do
      grocery_list_item = GroceryListItem.create! valid_attributes
      delete :destroy, {:id => grocery_list_item.to_param}, valid_session
      expect(response).to redirect_to(grocery_list_items_url)
    end
  end

end
