require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MemoriesController do
  before :each do
    as_user
    @ability.can :manage, Memory
    @ability.can :view_memories, User
  end

  # This should return the minimal set of attributes required to create a valid
  # Memory. As you add validations to Memory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    Factory.attributes_for(:memory)
  end

  describe "GET index" do
    it "assigns all memories as @memories" do
      memory = Factory(:memory, :user => @user)
      get :index
      assigns(:memories).should eq([memory])
    end
  end

  describe "GET show" do
    it "assigns the requested memory as @memory" do
      memory = Memory.create! valid_attributes
      get :show, :id => memory.id
      assigns(:memory).should eq(memory)
    end
  end

  describe "GET new" do
    it "assigns a new memory as @memory" do
      get :new
      assigns(:memory).should be_a_new(Memory)
    end
  end

  describe "GET edit" do
    it "assigns the requested memory as @memory" do
      memory = Memory.create! valid_attributes
      get :edit, :id => memory.id
      assigns(:memory).should eq(memory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Memory" do
        expect {
          post :create, :memory => valid_attributes
        }.to change(Memory, :count).by(1)
      end

      it "assigns a newly created memory as @memory" do
        post :create, :memory => valid_attributes
        assigns(:memory).should be_a(Memory)
        assigns(:memory).should be_persisted
      end

      it "redirects to the memory index" do
        post :create, :memory => valid_attributes
        response.should redirect_to(memories_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved memory as @memory" do
        # Trigger the behavior that occurs when invalid params are submitted
        Memory.any_instance.stub(:save).and_return(false)
        post :create, :memory => {}
        assigns(:memory).should be_a_new(Memory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Memory.any_instance.stub(:save).and_return(false)
        post :create, :memory => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested memory" do
        memory = Memory.create! valid_attributes
        # Assuming there are no other memories in the database, this
        # specifies that the Memory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Memory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => memory.id, :memory => {'these' => 'params'}
      end

      it "assigns the requested memory as @memory" do
        memory = Memory.create! valid_attributes
        put :update, :id => memory.id, :memory => valid_attributes
        assigns(:memory).should eq(memory)
      end

      it "redirects to the memory index" do
        memory = Memory.create! valid_attributes
        put :update, :id => memory.id, :memory => valid_attributes
        response.should redirect_to(memories_path)
      end
    end

    describe "with invalid params" do
      it "assigns the memory as @memory" do
        memory = Memory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Memory.any_instance.stub(:save).and_return(false)
        put :update, :id => memory.id, :memory => {}
        assigns(:memory).should eq(memory)
      end

      it "re-renders the 'edit' template" do
        memory = Memory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Memory.any_instance.stub(:save).and_return(false)
        put :update, :id => memory.id, :memory => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested memory" do
      memory = Memory.create! valid_attributes
      expect {
        delete :destroy, :id => memory.id
      }.to change(Memory, :count).by(-1)
    end

    it "redirects to the memories list" do
      memory = Memory.create! valid_attributes
      delete :destroy, :id => memory.id
      response.should redirect_to(memories_url)
    end
  end

end
