require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecordCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # RecordCategory. As you add validations to RecordCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all record_categories as @record_categories" do
      record_category = RecordCategory.create! valid_attributes
      get :index
      assigns(:record_categories).should eq([record_category])
    end
  end

  describe "GET show" do
    it "assigns the requested record_category as @record_category" do
      record_category = RecordCategory.create! valid_attributes
      get :show, :id => record_category.id
      assigns(:record_category).should eq(record_category)
    end
  end

  describe "GET new" do
    it "assigns a new record_category as @record_category" do
      get :new
      assigns(:record_category).should be_a_new(RecordCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested record_category as @record_category" do
      record_category = RecordCategory.create! valid_attributes
      get :edit, :id => record_category.id
      assigns(:record_category).should eq(record_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecordCategory" do
        expect {
          post :create, :record_category => valid_attributes
        }.to change(RecordCategory, :count).by(1)
      end

      it "assigns a newly created record_category as @record_category" do
        post :create, :record_category => valid_attributes
        assigns(:record_category).should be_a(RecordCategory)
        assigns(:record_category).should be_persisted
      end

      it "redirects to the created record_category" do
        post :create, :record_category => valid_attributes
        response.should redirect_to(RecordCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved record_category as @record_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecordCategory.any_instance.stub(:save).and_return(false)
        post :create, :record_category => {}
        assigns(:record_category).should be_a_new(RecordCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecordCategory.any_instance.stub(:save).and_return(false)
        post :create, :record_category => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested record_category" do
        record_category = RecordCategory.create! valid_attributes
        # Assuming there are no other record_categories in the database, this
        # specifies that the RecordCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecordCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => record_category.id, :record_category => {'these' => 'params'}
      end

      it "assigns the requested record_category as @record_category" do
        record_category = RecordCategory.create! valid_attributes
        put :update, :id => record_category.id, :record_category => valid_attributes
        assigns(:record_category).should eq(record_category)
      end

      it "redirects to the record_category" do
        record_category = RecordCategory.create! valid_attributes
        put :update, :id => record_category.id, :record_category => valid_attributes
        response.should redirect_to(record_category)
      end
    end

    describe "with invalid params" do
      it "assigns the record_category as @record_category" do
        record_category = RecordCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecordCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => record_category.id, :record_category => {}
        assigns(:record_category).should eq(record_category)
      end

      it "re-renders the 'edit' template" do
        record_category = RecordCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecordCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => record_category.id, :record_category => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested record_category" do
      record_category = RecordCategory.create! valid_attributes
      expect {
        delete :destroy, :id => record_category.id
      }.to change(RecordCategory, :count).by(-1)
    end

    it "redirects to the record_categories list" do
      record_category = RecordCategory.create! valid_attributes
      delete :destroy, :id => record_category.id
      response.should redirect_to(record_categories_url)
    end
  end

end
