require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TapLogRecordsController do

  # This should return the minimal set of attributes required to create a valid
  # TapLogRecord. As you add validations to TapLogRecord, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    Factory.attributes_for(:tap_log_record, :user => @user)
  end

  before :each do
    as_user
    @ability.can :manage, TapLogRecord
    @ability.can :view_tap_log_records, User
  end

  describe "GET index" do
    it "assigns all tap_log_records as @tap_log_records" do
      tap_log_record = TapLogRecord.create! valid_attributes
      get :index
      assigns(:tap_log_records).should eq([tap_log_record])
    end
  end

  describe "GET show" do
    it "assigns the requested tap_log_record as @tap_log_record" do
      tap_log_record = TapLogRecord.create! valid_attributes
      get :show, :id => tap_log_record.id
      assigns(:tap_log_record).should eq(tap_log_record)
    end
  end

  describe "GET new" do
    it "assigns a new tap_log_record as @tap_log_record" do
      get :new
      assigns(:tap_log_record).should be_a_new(TapLogRecord)
    end
  end

  describe "GET edit" do
    it "assigns the requested tap_log_record as @tap_log_record" do
      tap_log_record = TapLogRecord.create! valid_attributes
      get :edit, :id => tap_log_record.id
      assigns(:tap_log_record).should eq(tap_log_record)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TapLogRecord" do
        expect {
          post :create, :tap_log_record => valid_attributes
        }.to change(TapLogRecord, :count).by(1)
      end

      it "assigns a newly created tap_log_record as @tap_log_record" do
        post :create, :tap_log_record => valid_attributes
        assigns(:tap_log_record).should be_a(TapLogRecord)
        assigns(:tap_log_record).should be_persisted
      end

      it "redirects to the created tap_log_record" do
        post :create, :tap_log_record => valid_attributes
        response.should redirect_to(TapLogRecord.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tap_log_record as @tap_log_record" do
        # Trigger the behavior that occurs when invalid params are submitted
        TapLogRecord.any_instance.stub(:save).and_return(false)
        post :create, :tap_log_record => {}
        assigns(:tap_log_record).should be_a_new(TapLogRecord)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TapLogRecord.any_instance.stub(:save).and_return(false)
        post :create, :tap_log_record => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tap_log_record" do
        tap_log_record = TapLogRecord.create! valid_attributes
        # Assuming there are no other tap_log_records in the database, this
        # specifies that the TapLogRecord created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TapLogRecord.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => tap_log_record.id, :tap_log_record => {'these' => 'params'}
      end

      it "assigns the requested tap_log_record as @tap_log_record" do
        tap_log_record = TapLogRecord.create! valid_attributes
        put :update, :id => tap_log_record.id, :tap_log_record => valid_attributes
        assigns(:tap_log_record).should eq(tap_log_record)
      end

      it "redirects to the tap_log_record" do
        tap_log_record = TapLogRecord.create! valid_attributes
        put :update, :id => tap_log_record.id, :tap_log_record => valid_attributes
        response.should redirect_to(tap_log_record)
      end
    end

    describe "with invalid params" do
      it "assigns the tap_log_record as @tap_log_record" do
        tap_log_record = TapLogRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TapLogRecord.any_instance.stub(:save).and_return(false)
        put :update, :id => tap_log_record.id, :tap_log_record => {}
        assigns(:tap_log_record).should eq(tap_log_record)
      end

      it "re-renders the 'edit' template" do
        tap_log_record = TapLogRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TapLogRecord.any_instance.stub(:save).and_return(false)
        put :update, :id => tap_log_record.id, :tap_log_record => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tap_log_record" do
      tap_log_record = TapLogRecord.create! valid_attributes
      expect {
        delete :destroy, :id => tap_log_record.id
      }.to change(TapLogRecord, :count).by(-1)
    end

    it "redirects to the tap_log_records list" do
      tap_log_record = TapLogRecord.create! valid_attributes
      delete :destroy, :id => tap_log_record.id
      response.should redirect_to(tap_log_records_url)
    end
  end

end
